export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_ACCOUNT_TYPES = "GET_ACCOUNT_TYPES";
export const ADD_ACCOUNT_TYPE = "ADD_ACCOUNT_TYPE";
export const DELETE_ACCOUNT_TYPE = "DELETE_ACCOUNT_TYPE";

export const GET_ACCOUNT_CATEGORIES = "GET_ACCOUNT_CATEGORIES";
export const ADD_ACCOUNT_CATEGORY = "ADD_ACCOUNT_CATEGORY";
export const DELETE_ACCOUNT_CATEGORY = "DELETE_ACCOUNT_CATEGORY";

export const GET_ACCOUNT_SUB_CATEGORIES = "GET_ACCOUNT_SUB_CATEGORIES";
export const ADD_ACCOUNT_SUB_CATEGORY = "ADD_ACCOUNT_SUB_CATEGORY";
export const DELETE_ACCOUNT_SUB_CATEGORY = "DELETE_ACCOUNT_SUB_CATEGORY";

export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const ACCOUNTS_LOADING = "ACCOUNTS_LOADING";

export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const TRANSACTIONS_LOADING = "TRANSACTIONS_LOADING";
